name: TestCode Test

on:
  push:
    branches:
      - develop

jobs:
  Run-Jest:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setting
        run: npm install
      - name: Run Test Code
        run: npm run test
