name: Run Test Code

on:
  pull_request:
    branches:
      - release

jobs:
  Run-Jest:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setting
        run: npm install
      - name: run test code
        run: npm run test
