name: PR Test

on:
  # workflow_dispatch:
  # push:
  #   branches:
  #     - release
  pull_request:
    branches:
      - release

jobs:
  Run-Jest:
    runs-on: [ubuntu-latest]
    # strategy:
    #   matrix:
    #     node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: run test code
        run: npm run test
